const mcqData = {
  // --- FRONTEND ---
  html: [
    { id: "h1", question: "Which HTML element is used to specify a header for a document or section?", options: ["<top>", "<head>", "<header>", "<section>"], correctAnswer: 2, explanation: "The <header> element represents a container for introductory content or a set of navigational links." },
    { id: "h2", question: "What is the correct HTML for creating a hyperlink?", options: ["<a href=\"url\">Example</a>", "<a>url</a>", "<a url=\"url\">Example</a>", "<link href=\"url\">Example</link>"], correctAnswer: 0, explanation: "The <a> tag defines a hyperlink with the href attribute." },
    { id: "h3", question: "Which input type defines a slider control?", options: ["search", "range", "slider", "controls"], correctAnswer: 1, explanation: "<input type=\"range\"> defines a control for entering a number." },
    { id: "h4", question: "Choose the correct HTML element to define important text:", options: ["<important>", "<i>", "<strong>", "<b>"], correctAnswer: 2, explanation: "The <strong> tag defines important text." },
    { id: "h5", question: "Which character is used to indicate an end tag?", options: ["*", "^", "<", "/"], correctAnswer: 3, explanation: "The forward slash / is used to indicate an end tag, e.g., </p>." },
    { id: "h6", question: "How can you open a link in a new tab/browser window?", options: ["<a href=\"url\" target=\"new\">", "<a href=\"url\" target=\"_blank\">", "<a href=\"url\" new>", "<a href=\"url\" target=\"_new\">"], correctAnswer: 1, explanation: "The target=\"_blank\" attribute opens a link in a new tab." },
    { id: "h7", question: "Which of these elements are all <table> elements?", options: ["<table><head><tfoot >", "<table><tr><td>", "<thead><body><tr>", "<table><tr><tt>"], correctAnswer: 1, explanation: "<table>, <tr>, and <td> are all table elements." },
    { id: "h8", question: "How can you make a numbered list?", options: ["<ul>", "<dl>", "<ol>", "<list>"], correctAnswer: 2, explanation: "The <ol> tag defines an ordered (numbered) list." },
    { id: "h9", question: "What is the correct HTML for making a checkbox?", options: ["<checkbox>", "<input type=\"check\">", "<input type=\"checkbox\">", "<check>"], correctAnswer: 2, explanation: "<input type=\"checkbox\"> defines a checkbox." },
    { id: "h10", question: "What is the correct HTML for making a text input field?", options: ["<input type=\"text\">", "<input type=\"textfield\">", "<textinput>", "<textfield>"], correctAnswer: 0, explanation: "<input type=\"text\"> defines a single-line text input field." },
    { id: "h11", question: "What is the correct HTML for inserting an image?", options: ["<image src=\"image.gif\" alt=\"MyImage\">", "<img alt=\"MyImage\">image.gif</img>", "<img src=\"image.gif\" alt=\"MyImage\">", "<img href=\"image.gif\" alt=\"MyImage\">"], correctAnswer: 2, explanation: "The <img> tag is used to embed an image, requiring the src attribute." },
    { id: "h12", question: "Which HTML element defines the title of a document?", options: ["<meta>", "<title>", "<head>", "<header>"], correctAnswer: 1, explanation: "The <title> tag specifies the title of the document in the browser tab." },
    { id: "h13", question: "Which HTML attribute specifies an alternate text for an image, if the image cannot be displayed?", options: ["title", "alt", "src", "longdesc"], correctAnswer: 1, explanation: "The alt attribute provides alternative information for an image if a user cannot view it." },
    { id: "h14", question: "Which HTML element is used to specify a footer for a document or section?", options: ["<bottom>", "<footer>", "<section>", "<foot>"], correctAnswer: 1, explanation: "The <footer> tag defines a footer for a document or section." },
    { id: "h15", question: "In HTML, what does the <aside> element define?", options: ["Content aside from the page content", "A navigation list", "The ASCII character-set", "A blockquote"], correctAnswer: 0, explanation: "The <aside> element defines content aside from the page content (like a sidebar)." }
  ],
  css: [
    { id: "c1", question: "What does CSS stand for?", options: ["Computer Style Sheets", "Cascading Style Sheets", "Creative Style Sheets", "Colorful Style Sheets"], correctAnswer: 1, explanation: "CSS stands for Cascading Style Sheets." },
    { id: "c2", question: "What is the correct HTML for referring to an external style sheet?", options: ["<stylesheet>mystyle.css</stylesheet>", "<style src=\"mystyle.css\">", "<link rel=\"stylesheet\" type=\"text/css\" href=\"mystyle.css\">", "<link src=\"mystyle.css\">"], correctAnswer: 2, explanation: "The <link> tag with the href attribute is used for external CSS." },
    { id: "c3", question: "Where in an HTML document is the correct place to refer to an external style sheet?", options: ["In the <head> section", "At the end of the document", "In the <body> section", "In the <header> section"], correctAnswer: 0, explanation: "External style sheets should be linked in the <head> section." },
    { id: "c4", question: "Which HTML tag is used to define an internal style sheet?", options: ["<script>", "<css>", "<style>", "<link>"], correctAnswer: 2, explanation: "The <style> tag is used to define internal CSS." },
    { id: "c5", question: "Which HTML attribute is used to define inline styles?", options: ["styles", "style", "class", "font"], correctAnswer: 1, explanation: "The style attribute specifies an inline style for an element." },
    { id: "c6", question: "Which is the correct CSS syntax?", options: ["body {color: black;}", "{body:color=black;}", "body:color=black;", "{body;color:black;}"], correctAnswer: 0, explanation: "CSS syntax is: selector { property: value; }." },
    { id: "c7", question: "How do you insert a comment in a CSS file?", options: ["' this is a comment", "/* this is a comment */", "// this is a comment", "// this is a comment //"], correctAnswer: 1, explanation: "CSS comments start with /* and end with */." },
    { id: "c8", question: "Which property is used to change the background color?", options: ["color", "bgcolor", "background-color", "bg-color"], correctAnswer: 2, explanation: "The background-color property sets the background color." },
    { id: "c9", question: "How do you add a background color for all <h1> elements?", options: ["all.h1 {background-color:#FFFFFF;}", "h1.all {background-color:#FFFFFF;}", "h1 {background-color:#FFFFFF;}", "h1 {bgcolor:#FFFFFF;}"], correctAnswer: 2, explanation: "Use the tag name h1 as the selector." },
    { id: "c10", question: "Which CSS property is used to change the text color of an element?", options: ["text-color", "color", "fgcolor", "font-color"], correctAnswer: 1, explanation: "The color property changes the text color." },
    { id: "c11", question: "Which CSS property controls the text size?", options: ["font-style", "text-style", "font-size", "text-size"], correctAnswer: 2, explanation: "The font-size property sets the size of the text." },
    { id: "c12", question: "What is the correct CSS syntax for making all the <p> elements bold?", options: ["p {font-weight:bold;}", "p {text-size:bold;}", "<p style=\"text-size:bold;\">", "p {font:bold;}"], correctAnswer: 0, explanation: "font-weight: bold; is the correct syntax." },
    { id: "c13", question: "How do you display hyperlinks without an underline?", options: ["a {text-decoration:none;}", "a {underline:none;}", "a {decoration:no-underline;}", "a {text-decoration:no-underline;}"], correctAnswer: 0, explanation: "text-decoration: none; removes the underline from links." },
    { id: "c14", question: "How do you make each word in a text start with a capital letter?", options: ["text-transform:capitalize", "text-transform:uppercase", "transform:capitalize", "text-style:capitalize"], correctAnswer: 0, explanation: "text-transform: capitalize; capitalizes the first letter of each word." },
    { id: "c15", question: "How do you change the left margin of an element?", options: ["padding-left", "margin-left", "indent", "margin:"], correctAnswer: 1, explanation: "margin-left changes the left margin." }
  ],
  bootstrap: [
    { id: "b1", question: "Which class provides a responsive fixed width container?", options: [".container", ".container-fluid", ".container-fixed", ".container-responsive"], correctAnswer: 0, explanation: "The .container class provides a responsive fixed width container." },
    { id: "b2", question: "How many columns are there in the basic Bootstrap grid system?", options: ["8", "10", "12", "16"], correctAnswer: 2, explanation: "Bootstrap's grid system allows up to 12 columns across the page." },
    { id: "b3", question: "Which class creates a standard Bootstrap button?", options: [".btn", ".button", ".btn-standard", ".btn-default"], correctAnswer: 0, explanation: "The .btn class is the base class for all Bootstrap buttons." },
    { id: "b4", question: "Which class applies the primary color to text in Bootstrap?", options: [".text-blue", ".text-primary", ".font-primary", ".color-primary"], correctAnswer: 1, explanation: "The .text-primary class applies the primary theme color to text." },
    { id: "b5", question: "How do you create a flexbox container in Bootstrap?", options: [".d-flex", ".flex-container", ".display-flex", ".flex-box"], correctAnswer: 0, explanation: "The .d-flex class applies display: flex to the element." },
    { id: "b6", question: "Which class adds horizontal spacing (margin) to the left and right in Bootstrap 5?", options: [".mx", ".my", ".px", ".m-lr"], correctAnswer: 0, explanation: ".mx-* applies margin to the left and right (x-axis)." },
    { id: "b7", question: "What is the default break point for a large screen (lg) in Bootstrap?", options: ["576px", "768px", "992px", "1200px"], correctAnswer: 2, explanation: "The 'lg' breakpoint applies to screens ≥992px." },
    { id: "b8", question: "Which class hides an element on all screen sizes?", options: [".hidden", ".d-none", ".hide", ".invisible"], correctAnswer: 1, explanation: ".d-none sets display: none to hide the element." },
    { id: "b9", question: "Which class is used to create a responsive image that scales with its parent?", options: [".img-fluid", ".img-responsive", ".image-scale", ".img-fit"], correctAnswer: 0, explanation: "The .img-fluid class applies max-width: 100% and height: auto." },
    { id: "b10", question: "How do you center text using Bootstrap?", options: [".text-center", ".center-text", ".align-center", ".justify-content-center"], correctAnswer: 0, explanation: "The .text-center class aligns text to the center." },
    { id: "b11", question: "Which Bootstrap class indicates a success state (typically green)?", options: [".btn-good", ".btn-success", ".btn-green", ".btn-okay"], correctAnswer: 1, explanation: ".btn-success creates a button with the success theme color." },
    { id: "b12", question: "What class is used to make a round image?", options: [".img-circle", ".rounded-circle", ".circle-img", ".round"], correctAnswer: 1, explanation: ".rounded-circle makes the image a perfect circle." },
    { id: "b13", question: "How do you create a navigation bar in Bootstrap?", options: [".nav", ".navbar", ".navigation", ".menu"], correctAnswer: 1, explanation: "The .navbar class is the base wrapper for navigation bars." },
    { id: "b14", question: "Which class adds a shadow to an element?", options: [".shadow", ".drop-shadow", ".box-shadow", ".card-shadow"], correctAnswer: 0, explanation: "The .shadow class adds a default box-shadow." },
    { id: "b15", question: "How do you make a Bootstrap table striped?", options: [".table-striped", ".table-stripes", ".striped-table", ".table-alt"], correctAnswer: 0, explanation: ".table-striped adds zebra-striping to table rows." }
  ],
  javascript: [
    { id: "j1", question: "Inside which HTML element do we put the JavaScript?", options: ["<js>", "<javascript>", "<script>", "<scripting>"], correctAnswer: 2, explanation: "The <script> tag is used to embed a client-side script." },
    { id: "j2", question: "How do you create a function in JavaScript?", options: ["function:myFunction()", "function myFunction()", "function = myFunction()", "create myFunction()"], correctAnswer: 1, explanation: "A JavaScript function is defined with the function keyword." },
    { id: "j3", question: "Which of the following is NOT a JavaScript data type?", options: ["Number", "Boolean", "Float", "Undefined"], correctAnswer: 2, explanation: "JavaScript numbers are floating point, there is no explicit 'Float' type." },
    { id: "j4", question: "How do you write 'Hello World' in an alert box?", options: ["msg('Hello World');", "alertBox('Hello World');", "alert('Hello World');", "msgBox('Hello World');"], correctAnswer: 2, explanation: "The alert() function displays an alert box." },
    { id: "j5", question: "How to write an IF statement in JavaScript?", options: ["if i = 5 then", "if (i == 5)", "if i == 5 then", "if i = 5"], correctAnswer: 1, explanation: "The correct syntax is if (condition) { // code }." },
    { id: "j6", question: "How does a FOR loop start?", options: ["for (i = 0; i <= 5)", "for (i <= 5; i++)", "for i = 1 to 5", "for (i = 0; i <= 5; i++)"], correctAnswer: 3, explanation: "A for loop has three parts: initialization, condition, increment." },
    { id: "j7", question: "How can you add a comment in a JavaScript?", options: ["<!--This is a comment-->", "'This is a comment", "//This is a comment", "*This is a comment*"], correctAnswer: 2, explanation: "Double slashes // create a single-line comment." },
    { id: "j8", question: "What is the correct way to write a JavaScript array?", options: ["var colors = 1 = (\"red\"), 2 = (\"green\")", "var colors = [\"red\", \"green\", \"blue\"]", "var colors = \"red\", \"green\", \"blue\"", "var colors = (1:\"red\", 2:\"green\")"], correctAnswer: 1, explanation: "Arrays are defined using square brackets []." },
    { id: "j9", question: "How do you round the number 7.25, to the nearest integer?", options: ["Math.round(7.25)", "rnd(7.25)", "Math.rnd(7.25)", "round(7.25)"], correctAnswer: 0, explanation: "Math.round() rounds a number to the nearest integer." },
    { id: "j10", question: "How do you find the number with the highest value of x and y?", options: ["Math.max(x, y)", "Math.ceil(x, y)", "top(x, y)", "ceil(x, y)"], correctAnswer: 0, explanation: "Math.max() returns the highest value among arguments." },
    { id: "j11", question: "What event occurs when the user clicks on an HTML element?", options: ["onmouseclick", "onclick", "onchange", "onmouseover"], correctAnswer: 1, explanation: "The onclick event triggers when an element is clicked." },
    { id: "j12", question: "How do you declare a JavaScript variable?", options: ["v carName;", "variable carName;", "var carName;", "def carName;"], correctAnswer: 2, explanation: "Variables are declared with var, let, or const." },
    { id: "j13", question: "Which operator is used to assign a value to a variable?", options: ["*", "-", "=", "x"], correctAnswer: 2, explanation: "The equals sign = is the assignment operator." },
    { id: "j14", question: "What will typeof typeof 1 return?", options: ["'number'", "'string'", "'object'", "Syntax Error"], correctAnswer: 1, explanation: "typeof 1 returns 'number'. typeof 'number' returns 'string'." },
    { id: "j15", question: "Which method adds a new item to the end of an array?", options: ["push()", "pop()", "shift()", "add()"], correctAnswer: 0, explanation: "The push() method adds items to the end of an array." }
  ],
  react: [
    { id: "r1", question: "What is a React Hook?", options: ["A class component feature", "A function that lets you 'hook into' React state and lifecycle features", "A tool for routing", "An external library for state management"], correctAnswer: 1, explanation: "Hooks are functions that let you 'hook into' React state." },
    { id: "r2", question: "Which hook is used to perform side effects in a function component?", options: ["useEffect", "useState", "useReducer", "useSideEffect"], correctAnswer: 0, explanation: "useEffect allows you to perform side effects." },
    { id: "r3", question: "What is JSX?", options: ["A CSS preprocessor", "A JavaScript extension that allows you to write HTML inside JavaScript", "A testing framework", "A database query language"], correctAnswer: 1, explanation: "JSX stands for JavaScript XML." },
    { id: "r4", question: "How do you pass data from a parent component to a child component?", options: ["Using Context API", "Using Redux", "Using Props", "Using State"], correctAnswer: 2, explanation: "Props (properties) are used to pass data down the component tree." },
    { id: "r5", question: "What does the useState hook return?", options: ["A state object and a function to update it", "A single value representing the state", "An array with two elements: the current state value and a state updater function", "A boolean indicating if state changed"], correctAnswer: 2, explanation: "useState returns an array: [stateValue, setStateFunction]." },
    { id: "r6", question: "What is the virtual DOM?", options: ["A direct copy of the actual DOM", "A lightweight, in-memory representation of the real DOM", "A CSS manipulation tool", "A browser extension"], correctAnswer: 1, explanation: "React uses a Virtual DOM to optimize rendering performance." },
    { id: "r7", question: "In React, what are components?", options: ["Functions that return HTML", "Independent, reusable pieces of the UI", "CSS stylesheets", "Database queries"], correctAnswer: 1, explanation: "Components are the building blocks of a React application." },
    { id: "r8", question: "How can you handle forms in React?", options: ["Using standard HTML forms", "Using Controlled Components", "React does not support forms", "Using only Uncontrolled Components"], correctAnswer: 1, explanation: "Controlled components tie form data directly to React state." },
    { id: "r9", question: "What is the purpose of the 'key' prop in React lists?", options: ["To define CSS styles", "To help React identify which items have changed, been added, or removed", "To pass data to children", "To sort the list"], correctAnswer: 1, explanation: "Keys give list elements a stable identity." },
    { id: "r10", question: "Can a React component return multiple elements without a wrapping element?", options: ["Yes, natively", "Yes, using React Fragments (<>...</>)", "No, it must always be a <div>", "No, it must be an array"], correctAnswer: 1, explanation: "React Fragments let you group elements without adding extra nodes." },
    { id: "r11", question: "What is Context API used for?", options: ["Routing", "Styling", "Passing data deeply through the component tree without prop drilling", "Fetching APIs"], correctAnswer: 2, explanation: "Context API provides a way to share values like themes or user info globally." },
    { id: "r12", question: "What hook should you use to memorize an expensive calculation?", options: ["useMemo", "useCallback", "useEffect", "useState"], correctAnswer: 0, explanation: "useMemo memorizes the result of a calculation." },
    { id: "r13", question: "How do you conditionally render a component?", options: ["Using standard if/else statements or ternary operators inside the render method", "Using the <Cond> component", "Using CSS display: none", "You cannot conditionally render"], correctAnswer: 0, explanation: "Ternary operators and && are commonly used in JSX." },
    { id: "r14", question: "Which method is used in a class component to update state?", options: ["updateState()", "changeState()", "setState()", "modifyState()"], correctAnswer: 2, explanation: "this.setState() is used to update state in class components." },
    { id: "r15", question: "What package is commonly used for routing in React?", options: ["react-router-dom", "react-navigation", "react-routes", "react-navigator"], correctAnswer: 0, explanation: "react-router-dom is the standard routing library for web." }
  ],

  // --- BACKEND ---
  python: [
    { id: "p1", question: "What is a correct syntax to output 'Hello World' in Python?", options: ["p('Hello World')", "echo 'Hello World'", "print('Hello World')", "console.log('Hello World')"], correctAnswer: 2, explanation: "print() is the built-in function to output text." },
    { id: "p2", question: "How do you insert comments in Python code?", options: ["// This is a comment", "/* This is a comment */", "# This is a comment", "-- This is a comment"], correctAnswer: 2, explanation: "Comments in Python start with a hash (#)." },
    { id: "p3", question: "Which one is NOT a legal variable name?", options: ["my_var", "my-var", "_myvar", "myvar"], correctAnswer: 1, explanation: "Variable names cannot contain hyphens (-)." },
    { id: "p4", question: "How do you create a variable with the numeric value 5?", options: ["x = int(5)", "x = 5", "Both of these", "None of these"], correctAnswer: 2, explanation: "Both create a variable containing the integer 5." },
    { id: "p5", question: "What is the correct file extension for Python files?", options: [".pyt", ".py", ".pt", ".python"], correctAnswer: 1, explanation: "Python files use the .py extension." }
  ],
  django: [
    { id: "dj1", question: "What is Django?", options: ["A JavaScript library", "A high-level Python Web framework", "A database", "A cloud platform"], correctAnswer: 1, explanation: "Django is a Python web framework." },
    { id: "dj2", question: "What design pattern does Django loosely follow?", options: ["MVC", "MVT", "MVVM", "Singleton"], correctAnswer: 1, explanation: "Django follows the Model-View-Template (MVT) pattern." },
    { id: "dj3", question: "How do you create a new Django project?", options: ["django-admin startproject myproject", "python manage.py newproject", "django new myproject", "django init myproject"], correctAnswer: 0, explanation: "django-admin startproject initializes a new project." },
    { id: "dj4", question: "What is manage.py?", options: ["A config file", "A command-line utility that lets you interact with your project", "A database file", "A routing module"], correctAnswer: 1, explanation: "manage.py provides commands like runserver, makemigrations, etc." },
    { id: "dj5", question: "What does the 'makemigrations' command do?", options: ["Creates database tables", "Creates new migrations based on the changes you have made to your models", "Runs the server", "Deletes old database records"], correctAnswer: 1, explanation: "makemigrations packages model changes into migration files." }
  ],
  flask: [
    { id: "fl1", question: "What is Flask?", options: ["A full-stack framework", "A micro web framework written in Python", "A database", "An API testing tool"], correctAnswer: 1, explanation: "Flask is a lightweight WSGI web application framework." },
    { id: "fl2", question: "How do you define a route in Flask?", options: ["@app.route('/')", "app.setRoute('/')", "app.get('/')", "route('/')"], correctAnswer: 0, explanation: "The @app.route() decorator binds a URL to a function." },
    { id: "fl3", question: "What templating engine does Flask use by default?", options: ["Django Templates", "Jinja2", "EJS", "Handlebars"], correctAnswer: 1, explanation: "Flask comes bundled with the Jinja2 templating engine." },
    { id: "fl4", question: "How do you start a development server in Flask?", options: ["flask start", "python app.py (if app.run() is present)", "npm run start", "manage.py runserver"], correctAnswer: 1, explanation: "Running the script executing app.run() starts the server." },
    { id: "fl5", question: "Which object gives access to incoming request data in Flask?", options: ["flask.Request", "flask.request", "flask.req", "flask.data"], correctAnswer: 1, explanation: "The global request object contains incoming request data." }
  ],
  restapi: [
    { id: "ra1", question: "What does REST stand for?", options: ["Representational State Transfer", "Remote State Transfer", "Representational Server Transfer", "Remote Server Transfer"], correctAnswer: 0, explanation: "REST is an architectural style for distributed systems." },
    { id: "ra2", question: "Which HTTP method is used to read data?", options: ["POST", "GET", "PUT", "DELETE"], correctAnswer: 1, explanation: "GET is used to request data from a specified resource." },
    { id: "ra3", question: "Which HTTP method is used to completely replace an existing resource?", options: ["PATCH", "POST", "PUT", "GET"], correctAnswer: 2, explanation: "PUT replaces the resource entirely, while PATCH updates partially." },
    { id: "ra4", question: "What is a 404 status code?", options: ["Server Error", "Not Found", "Unauthorized", "OK"], correctAnswer: 1, explanation: "404 indicates the requested resource could not be found." },
    { id: "ra5", question: "What format is most commonly used to send and receive data in a REST API?", options: ["XML", "JSON", "HTML", "YAML"], correctAnswer: 1, explanation: "JSON (JavaScript Object Notation) is the standard format." }
  ],

  // --- CLOUD ---
  aws: [
    { id: "aw1", question: "What is Amazon EC2?", options: ["A database service", "A virtual server in the cloud", "A storage service", "A networking tool"], correctAnswer: 1, explanation: "Amazon Elastic Compute Cloud (EC2) provides scalable computing capacity." },
    { id: "aw2", question: "Which service is used for object storage in AWS?", options: ["EC2", "RDS", "S3", "Lambda"], correctAnswer: 2, explanation: "Amazon S3 (Simple Storage Service) is an object storage service." },
    { id: "aw3", question: "What does IAM stand for?", options: ["Identity and Access Management", "Internal Access Monitor", "Internet Access Manager", "Identity Auth Module"], correctAnswer: 0, explanation: "IAM enables you to securely control access to AWS services." },
    { id: "aw4", question: "Which AWS service is fully managed relational database service?", options: ["DynamoDB", "Redshift", "RDS", "S3"], correctAnswer: 2, explanation: "Amazon Relational Database Service (RDS) manages relational databases." },
    { id: "aw5", question: "What is AWS Lambda?", options: ["A serverless compute service", "A container registry", "A load balancer", "A virtual private cloud"], correctAnswer: 0, explanation: "Lambda runs code without provisioning or managing servers." }
  ],
  azure: [
    { id: "az1", question: "What is Azure Virtual Machines?", options: ["IaaS for running Windows or Linux in the cloud", "A database service", "A serverless function", "A domain registrar"], correctAnswer: 0, explanation: "Azure VMs provide on-demand, scalable computing resources." },
    { id: "az2", question: "What is Azure Blob Storage?", options: ["A relational database", "Object storage for the cloud", "A messaging queue", "A virtual network"], correctAnswer: 1, explanation: "Blob storage is Microsoft's object storage solution for the cloud." },
    { id: "az3", question: "Which service allows you to run event-driven serverless code in Azure?", options: ["Azure VMs", "Azure Functions", "Azure App Service", "Azure Cosmos DB"], correctAnswer: 1, explanation: "Azure Functions is a serverless compute service." },
    { id: "az4", question: "What is Azure Cosmos DB?", options: ["A fully managed NoSQL database", "A relational SQL database", "A storage account", "An active directory"], correctAnswer: 0, explanation: "Cosmos DB is Microsoft's globally distributed, multi-model database service." },
    { id: "az5", question: "What service is used for identity management in Azure?", options: ["Azure IAM", "Microsoft Entra ID (formerly Azure Active Directory)", "Azure SSO", "Azure Users"], correctAnswer: 1, explanation: "Microsoft Entra ID is the cloud-based identity and access management service." }
  ],
  docker: [
    { id: "dk1", question: "What is a Docker container?", options: ["A full virtual machine", "A lightweight, standalone, executable package of software", "A database", "A continuous integration tool"], correctAnswer: 1, explanation: "Containers package code and all its dependencies." },
    { id: "dk2", question: "Which file is used to define how a Docker image is built?", options: ["docker-compose.yml", "Dockerfile", "package.json", "Makefile"], correctAnswer: 1, explanation: "A Dockerfile contains all commands needed to build a given image." },
    { id: "dk3", question: "What does the 'docker ps' command do?", options: ["Starts a container", "Lists all running containers", "Builds an image", "Pushes an image to a registry"], correctAnswer: 1, explanation: "docker ps lists currently running containers." },
    { id: "dk4", question: "What is Docker Compose used for?", options: ["Building single images", "Defining and running multi-container Docker applications", "Deploying to production", "Managing Kubernetes clusters"], correctAnswer: 1, explanation: "Docker Compose uses a YAML file to configure application services." },
    { id: "dk5", question: "What is a Docker image?", options: ["A running instance of a container", "A read-only template with instructions for creating a container", "A storage volume", "A network interface"], correctAnswer: 1, explanation: "Images are the templates from which containers are launched." }
  ],
  kubernetes: [
    { id: "kb1", question: "What is Kubernetes?", options: ["A programming language", "An open-source container orchestration engine", "A virtual machine manager", "A cloud provider"], correctAnswer: 1, explanation: "Kubernetes automates deployment, scaling, and management of containerized applications." },
    { id: "kb2", question: "What is the smallest deployable unit in Kubernetes?", options: ["Container", "Node", "Pod", "Cluster"], correctAnswer: 2, explanation: "A Pod represents a single instance of a running process in your cluster." },
    { id: "kb3", question: "Which command-line tool is used to interact with Kubernetes clusters?", options: ["kubed", "k8s-cli", "kubectl", "kube-admin"], correctAnswer: 2, explanation: "kubectl is the Kubernetes command-line tool." },
    { id: "kb4", question: "What does a Deployment do in Kubernetes?", options: ["Manages network traffic", "Provides declarative updates for Pods and ReplicaSets", "Stores secrets", "Monitors logs"], correctAnswer: 1, explanation: "Deployments manage the desired state for your pods." },
    { id: "kb5", question: "What is a Kubernetes Service?", options: ["A physical server", "An abstract way to expose an application running on a set of Pods", "A database", "A billing tier"], correctAnswer: 1, explanation: "Services enable network access to a set of Pods." }
  ]
};

export default mcqData;
